### ISSUE TITLE
Training data access

### ISSUE THREAD

**Issue by VladPetk** [asigalov61/GIGA-Piano-XL#1]
Hi Alex,

Thanks for all the cool work you've been doing on symbolic music generation!

Do you still have access to the data used to train the Giga-Piano-XL model? The link in the [repository ](https://github.com/asigalov61/GIGA-Piano-XL/tree/main/Training-Data) appears to be dead. 

I'd like to try training a piano model using BPE for tokens and a "newer" architecture (X transformers), but can't find as much data as you seem to have collected. Incidentally, have you tried using BPE or embedding pooling? I've read it can improve the performance for such tasks.

**Comment by asigalov61** [comment]
@VladPetk Hi Vlad,

Thank you for appreciating my work. It means a lot to me :)

Yes, original pre-processed training data is not being provided anymore for many different reasons (I need to remove that link from a repo to avoid confusion).

However, all MIDI datasets used to train GIGA-Piano are listed and still available here:
https://github.com/asigalov61/Tegridy-MIDI-Dataset

Main datasets that you should use would be Giant MIDI, ASAP and ATEPP. And if you need more, you can add MAESTRO, POP. For even more data, you can extract Piano from standard datasets such as LAKH, MMD. or my Los Angeles MIDI dataset.

As far as BPE/embedding pooling...I have not used such approaches but it is definitely possible that they help to improve the generated output. From my experience, improvements in generated output usually depend on seq_len and size of the model (more == better) and other techniques usually do not improve the results (at least in a significant/noticieable way).

Hope this helps and answers your questions. But feel free to ask more info, if needed :) Would be happy to assist. :)

Alex

**Comment by VladPetk** [comment]
Hi Alex,

Thanks for the reply! Great, I'll use the the datasets you've pointed too.

I'll try to do model comparison with and without BPE (and also perhaps embedding pooling if I want to deal with multiples losses) when I have time. I'll let you know when I have the results, if you're interested. 

Vlad

**Comment by asigalov61** [comment]
@VladPetk You are welcome :)

Yes, please let me know the comparison results. I am always on lookout for techniques that improve the output quality.

Alex.

**Comment by asigalov61** [comment]
@VladPetk I have updated Training Data section with the link to Tegridy MIDI Dataset. So I am closing this issue for now.

If you will have an update on BPE/embedding pooling comparison, feel free to open a discussion in the Discussion section.

Thanks.

Alex.
